# Generated by Django 2.2 on 2020-04-25 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20200411_1729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecolumn',
            options={'verbose_name_plural': '专栏'},
        ),
    ]
